theme: jekyll-theme-cayman
# see https://github.com/pages-themes/cayman
title: FemDwell Project
description: description

defaults:
- scope: 
    path: "*.md"
  values:
    layout: "default"

optional_front_matter:
  enabled: true

optional_front_matter:
  remove_originals: true


